version: '3.8'

services:
  postgres:
    image: postgres:18.1-alpine
    container_name: giftbox_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_INITDB_ARGS: "-E UTF8"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - giftbox_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: giftbox_pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@giftbox.com}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
  #   ports:
  #     - "${PGADMIN_PORT:-5050}:80"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - giftbox_network
  #   restart: unless-stopped

volumes:
  postgres_data:


networks:
  giftbox_network:
    driver: bridge
